# Generated by Django 6.0.3 on 2026-06-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_shippingzone_order_discount_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('incoming', 'Pedido Entrante'), ('pending_payment', 'Pendiente de Pago'), ('in_production', 'En Fabricación'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
