# Generated by Django 6.0.4 on 2026-06-09 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_continent_shippingzone_continent_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingzone',
            name='extra_per_item',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='shipping_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='orders.shippingzone'),
        ),
    ]
